---
title: "STA 570 -- Ch. 7 Homework"
author: "Brit Riggs, Anirban Chetia"
date: "`r format(Sys.time(),  '%B %d, %Y')`"
output: pdf_document
---

# Help

I understand all of the problems!

```{r, message = FALSE, warning = FALSE, echo = FALSE}
suppressPackageStartupMessages({
library(knitr)
library(dplyr)
library(boot)
library(mosaic)
library(ggplot2)
})
```
# Exercise 1

## 1a

$\delta = \bar{x}_{1} - \bar{x}_{2}$  
$H_{0}: \delta = 0$  
$H_{a}: \delta > 0$  

```{r}
# fracking
n1    <- 21
xbar1 <- 19.2
s1    <- 30.3

# no fracking
n2    <- 13
xbar2 <- 1.1
s2    <- 6.3

alpha <- 0.05

# b
V1 <- s1^2/n1
V2 <- s2^2/n2
std_err <- sqrt( V1 + V2 )

(test_statistic <- ( xbar1 - xbar2 ) / std_err)
special_df <- ( (V1 + V2)^2 ) / ( (V1^2/n1-1) + (V2^2/n2-1) )

# c
(1-pt(test_statistic, df=special_df))
```
## 1d  
we reject the null because p-val < alpha  


## 1e  
We reject that sites near fracking wells have the same methane levels as sites far from fracking wells. This means that we do have evidence supporting that methane levels are higher near fracking wells.

\textbf{GOT IT}

# Exercise 2

$\delta = \bar{y} - \bar{x}$  
$H_{0}: \delta = 0$  
$H_{a}: \delta > 0$  
        
```{r}
# male
ny <- 30
ybar <- 350000
sy   <- 61900

# female
nx <- 30
xbar <- 245000
sx   <- 52100

# c
s_pool_squared <- (1/(ny + nx - 2))*( ((ny-1)*sy^2) + ((nx-1)*sx^2) )

(test_statistic <- (ybar - xbar) / sqrt( (s_pool_squared/ny) + (s_pool_squared/nx) ))

# d
(1-pt(test_statistic, df=ny+nx-2))
```
## 2d  
we reject the null because p-val < alpha  


## 2e  
We reject that female and male candidates generally raise the same amount in their campaigns. This means that we do have evidence supporting that women generally raise less than male candidates.


\textbf{GOT IT}

# Exercise 3

```{r}
data(Smiles, package="Lock5Data")

Smiles %>% summarise(xbar=)
```

\textbf{GOT IT}

# Exercise 4

## 4a

```{r}

```




```{r}
quantile(Boot.FloridaLakes$t, probs = c(.025, .925))
```

\textbf{GOT IT}

## 4b

```{r}

```



```{r}

```

## 4c

# Exercise 5

## 5a

```{r}

```


```{r}

```

## 5b


```{r}

```


```{r}

```

## 5c


## 5d

Required confidence interval:
$$
\left(\bar{x}_{1}-\bar{x}_{2}\right)\pm t_{n_{1}+n_{2}-2}^{1-\alpha/2}\;\left(s_{pool}\sqrt{\frac{1}{n_{1}}+\frac{1}{n_{2}}}\right)
$$
